/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TTgen0.ExtraForms;

/**
 *
 * @author ragha
 */
public class ExtraForm extends javax.swing.JFrame {

    /**
     * Creates new form ExtraForm
     */
    public ExtraForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        P61 = new javax.swing.JLabel();
        P62 = new javax.swing.JLabel();
        P63 = new javax.swing.JLabel();
        P64 = new javax.swing.JLabel();
        P65 = new javax.swing.JLabel();
        P66 = new javax.swing.JLabel();
        T61 = new javax.swing.JLabel();
        T62 = new javax.swing.JLabel();
        T63 = new javax.swing.JLabel();
        T64 = new javax.swing.JLabel();
        T65 = new javax.swing.JLabel();
        T66 = new javax.swing.JLabel();
        P51 = new javax.swing.JLabel();
        P52 = new javax.swing.JLabel();
        P53 = new javax.swing.JLabel();
        P54 = new javax.swing.JLabel();
        P55 = new javax.swing.JLabel();
        T51 = new javax.swing.JLabel();
        T52 = new javax.swing.JLabel();
        T53 = new javax.swing.JLabel();
        T54 = new javax.swing.JLabel();
        T55 = new javax.swing.JLabel();
        P41 = new javax.swing.JLabel();
        P42 = new javax.swing.JLabel();
        P43 = new javax.swing.JLabel();
        P44 = new javax.swing.JLabel();
        T41 = new javax.swing.JLabel();
        T42 = new javax.swing.JLabel();
        T43 = new javax.swing.JLabel();
        T44 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P61.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        P61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P61.setText("1");
        jPanel1.add(P61, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 64, 128, 20));

        P62.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        P62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P62.setText("2");
        jPanel1.add(P62, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 64, 127, 20));

        P63.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        P63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P63.setText("3");
        jPanel1.add(P63, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 64, 127, 20));

        P64.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        P64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P64.setText("4");
        jPanel1.add(P64, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 64, 127, 20));

        P65.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        P65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P65.setText("5");
        jPanel1.add(P65, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 64, 127, 20));

        P66.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        P66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P66.setText("6");
        jPanel1.add(P66, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 64, 127, 20));

        T61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T61.setText("jLabel1");
        jPanel1.add(T61, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 83, 128, 12));

        T62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T62.setText("jLabel1");
        jPanel1.add(T62, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 83, 128, 12));

        T63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T63.setText("jLabel1");
        jPanel1.add(T63, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 83, 128, 12));

        T64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T64.setText("jLabel1");
        jPanel1.add(T64, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 83, 134, 12));

        T65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T65.setText("jLabel1");
        jPanel1.add(T65, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 83, 130, 12));

        T66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T66.setText("jLabel1");
        jPanel1.add(T66, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 83, 128, 12));

        P51.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        P51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P51.setText("1");
        jPanel1.add(P51, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 64, 154, 20));

        P52.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        P52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P52.setText("2");
        jPanel1.add(P52, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 64, 154, 20));

        P53.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        P53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P53.setText("3");
        jPanel1.add(P53, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 64, 154, 20));

        P54.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        P54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P54.setText("4");
        jPanel1.add(P54, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 64, 154, 20));

        P55.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        P55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P55.setText("5");
        jPanel1.add(P55, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 64, 154, 20));

        T51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T51.setText("jLabel1");
        jPanel1.add(T51, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 84, 154, 12));

        T52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T52.setText("jLabel1");
        jPanel1.add(T52, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 84, 154, 12));

        T53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T53.setText("jLabel1");
        jPanel1.add(T53, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 84, 154, 12));

        T54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T54.setText("jLabel1");
        jPanel1.add(T54, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 84, 154, 12));

        T55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T55.setText("jLabel1");
        jPanel1.add(T55, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 84, 154, 12));

        P41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        P41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P41.setText("1");
        jPanel1.add(P41, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 64, 194, 20));

        P42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        P42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P42.setText("2");
        P42.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(P42, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 64, 194, 20));

        P43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        P43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P43.setText("3");
        jPanel1.add(P43, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 64, 194, 20));

        P44.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        P44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        P44.setText("4");
        jPanel1.add(P44, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 64, 194, 20));

        T41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T41.setText("jLabel1");
        jPanel1.add(T41, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 84, 194, 12));

        T42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T42.setText("jLabel1");
        jPanel1.add(T42, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 84, 194, 12));

        T43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T43.setText("jLabel1");
        jPanel1.add(T43, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 84, 194, 12));

        T44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        T44.setText("jLabel1");
        jPanel1.add(T44, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 84, 194, 12));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExtraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExtraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExtraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExtraForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExtraForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel P41;
    private javax.swing.JLabel P42;
    private javax.swing.JLabel P43;
    private javax.swing.JLabel P44;
    private javax.swing.JLabel P51;
    private javax.swing.JLabel P52;
    private javax.swing.JLabel P53;
    private javax.swing.JLabel P54;
    private javax.swing.JLabel P55;
    private javax.swing.JLabel P61;
    private javax.swing.JLabel P62;
    private javax.swing.JLabel P63;
    private javax.swing.JLabel P64;
    private javax.swing.JLabel P65;
    private javax.swing.JLabel P66;
    private javax.swing.JLabel T41;
    private javax.swing.JLabel T42;
    private javax.swing.JLabel T43;
    private javax.swing.JLabel T44;
    private javax.swing.JLabel T51;
    private javax.swing.JLabel T52;
    private javax.swing.JLabel T53;
    private javax.swing.JLabel T54;
    private javax.swing.JLabel T55;
    private javax.swing.JLabel T61;
    private javax.swing.JLabel T62;
    private javax.swing.JLabel T63;
    private javax.swing.JLabel T64;
    private javax.swing.JLabel T65;
    private javax.swing.JLabel T66;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
