/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TTgen0;

import static TTgen0.ClassesDatabase.ClassIds;
import static TTgen0.Other.Days;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author ragha
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    Connection myCon=null;
    Statement myStat=null;
    ResultSet myResult=null,myResult1=null;
    String TableName0,TableName1,TableName2;
    
    public Dashboard() {
        initComponents();
        
        new Other().setVisible(false);
        new RoomsDatabase().setVisible(false);
        new ClassesDatabase().setVisible(false);
        new TeachersDatabase().setVisible(false);
        new SubjectsDatabase().setVisible(false);
        
        TableName0=(Other.CourseName.getText()+"_"+Other.Branch.getText()+"_"+Other.Year.getText()+"_subjects_tt_record").toUpperCase();        
        TableName1=(Other.CourseName.getText()+"_"+Other.Branch.getText()+"_"+Other.Year.getText()+"_teachers_tt_record").toUpperCase();        
        TableName2=(Other.CourseName.getText()+"_"+Other.Branch.getText()+"_"+Other.Year.getText()+"_rooms_tt_record").toUpperCase();        

        viewpane.setEnabled(false);
        viewpane.setVisible(false);
        set2.setEnabled(false);
        set2.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Classrooms = new javax.swing.JButton();
        Subjects = new javax.swing.JButton();
        Classes = new javax.swing.JButton();
        Teachers = new javax.swing.JButton();
        OtherInfo = new javax.swing.JButton();
        set1 = new javax.swing.JLabel();
        set2 = new javax.swing.JLabel();
        viewpane = new javax.swing.JPanel();
        LogOrReg = new javax.swing.JButton();
        DataView = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        viewsetting = new javax.swing.JLabel();
        User = new javax.swing.JButton();
        StudentPreview = new javax.swing.JButton();
        TeacherPreview = new javax.swing.JButton();
        GenerateTT = new javax.swing.JButton();
        Help = new javax.swing.JButton();
        About = new javax.swing.JButton();
        Settings2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelInfo.setEditable(false);
        WelInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        WelInfo.setBorder(null);
        WelInfo.setOpaque(false);
        jPanel1.add(WelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 220, 30));
        WelInfo.getAccessibleContext().setAccessibleParent(WelInfo);

        Classrooms.setBorderPainted(false);
        Classrooms.setContentAreaFilled(false);
        Classrooms.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Classrooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClassroomsMouseClicked(evt);
            }
        });
        jPanel1.add(Classrooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 20));

        Subjects.setBorderPainted(false);
        Subjects.setContentAreaFilled(false);
        Subjects.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Subjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubjectsMouseClicked(evt);
            }
        });
        jPanel1.add(Subjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 135, 120, 20));

        Classes.setBorderPainted(false);
        Classes.setContentAreaFilled(false);
        Classes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Classes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClassesMouseClicked(evt);
            }
        });
        jPanel1.add(Classes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 168, 120, 20));

        Teachers.setBorderPainted(false);
        Teachers.setContentAreaFilled(false);
        Teachers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Teachers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TeachersMouseClicked(evt);
            }
        });
        Teachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeachersActionPerformed(evt);
            }
        });
        jPanel1.add(Teachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 202, 120, 20));

        OtherInfo.setBorderPainted(false);
        OtherInfo.setContentAreaFilled(false);
        OtherInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OtherInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OtherInfoMouseClicked(evt);
            }
        });
        jPanel1.add(OtherInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 120, 20));

        set1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        set1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                set1MouseClicked(evt);
            }
        });
        jPanel1.add(set1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 505, 62, 35));

        set2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        set2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                set2MouseClicked(evt);
            }
        });
        jPanel1.add(set2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 505, 62, 35));

        viewpane.setLayout(null);

        LogOrReg.setBorderPainted(false);
        LogOrReg.setContentAreaFilled(false);
        LogOrReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewpane.add(LogOrReg);
        LogOrReg.setBounds(10, 10, 140, 30);

        DataView.setBorderPainted(false);
        DataView.setContentAreaFilled(false);
        DataView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewpane.add(DataView);
        DataView.setBounds(10, 55, 140, 30);

        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        viewpane.add(exit);
        exit.setBounds(10, 100, 140, 30);

        viewsetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/settings.JPG"))); // NOI18N
        viewsetting.setText("jLabel2");
        viewpane.add(viewsetting);
        viewsetting.setBounds(0, 0, 160, 140);

        jPanel1.add(viewpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 160, 140));
        viewpane.getAccessibleContext().setAccessibleParent(viewpane);

        User.setBorderPainted(false);
        User.setContentAreaFilled(false);
        User.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 505, 62, 35));

        StudentPreview.setBorderPainted(false);
        StudentPreview.setContentAreaFilled(false);
        StudentPreview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StudentPreview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentPreviewMouseClicked(evt);
            }
        });
        jPanel1.add(StudentPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 100, 50));

        TeacherPreview.setBorderPainted(false);
        TeacherPreview.setContentAreaFilled(false);
        TeacherPreview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TeacherPreview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TeacherPreviewMouseClicked(evt);
            }
        });
        TeacherPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherPreviewActionPerformed(evt);
            }
        });
        jPanel1.add(TeacherPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 202, 100, 50));

        GenerateTT.setBorderPainted(false);
        GenerateTT.setContentAreaFilled(false);
        GenerateTT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(GenerateTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 100, 50));

        Help.setBorderPainted(false);
        Help.setContentAreaFilled(false);
        Help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 445, 100, 50));

        About.setBorderPainted(false);
        About.setContentAreaFilled(false);
        About.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutMouseClicked(evt);
            }
        });
        jPanel1.add(About, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 445, 100, 50));

        Settings2.setBorderPainted(false);
        Settings2.setContentAreaFilled(false);
        Settings2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Settings2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 100, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dashboard2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeachersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeachersActionPerformed

    private void TeacherPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherPreviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeacherPreviewActionPerformed

    private void set1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_set1MouseClicked
        viewpane.setEnabled(true);
        viewpane.setVisible(true);
        set1.setEnabled(false);
        set1.setVisible(false);
        set2.setEnabled(true);
        set2.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_set1MouseClicked

    private void set2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_set2MouseClicked
        viewpane.setEnabled(false);
        viewpane.setVisible(false);
        set1.setEnabled(true);
        set1.setVisible(true);
        set2.setEnabled(false);
        set2.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_set2MouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void ClassroomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClassroomsMouseClicked
        this.dispose();
        new RoomsDatabase().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ClassroomsMouseClicked

    private void SubjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubjectsMouseClicked
        this.dispose();
        new SubjectsDatabase().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_SubjectsMouseClicked

    private void ClassesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClassesMouseClicked
        this.dispose();
        new ClassesDatabase().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_ClassesMouseClicked

    private void TeachersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeachersMouseClicked
        this.dispose();
        new TeachersDatabase().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_TeachersMouseClicked

    private void AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutMouseClicked
    this.dispose();
    new AboutUs().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AboutMouseClicked

    private void OtherInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OtherInfoMouseClicked
    this.dispose();
    new Other().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_OtherInfoMouseClicked
    
    public void CreateSubjectsRecordTable(){

    String[] dayNames=new String[]{"Mo","Tu","We","Th","Fr","Sa","Su"};
        if(ClassIds.length>0){
            try{
                        myCon=DriverManager.getConnection("jdbc:derby://localhost:1527/TTgen","rg","1234");
                        myStat=myCon.createStatement();
                        DatabaseMetaData dbm =myCon.getMetaData();
                        ResultSet tables = dbm.getTables(null, null, TableName0, null);
                        String query="create table "+TableName0+" (DAYS VARCHAR(10),";
                        String query1="insert into "+TableName0+" values(?,";

                        for(int k=0;k<ClassIds.length;k++){
                        query=query+ClassIds[k]+" VARCHAR(100),";
                        }
                        query=query.substring(0, query.length()-1)+")";

                        for(int k=0;k<ClassIds.length;k++){
                        query1=query1+"?,";
                        }
                        query1=query1.substring(0, query1.length()-1)+")";


                        if(!tables.next()){
                        myStat=myCon.createStatement();
                        myStat.executeUpdate(query);
                        }

                        for(int i=0;i<Days.getRowCount();i++){
                            for(int j=1;j<=8;j++){                    
                                PreparedStatement insert=(PreparedStatement) myCon.prepareStatement(query1);
                                insert.setString(1,dayNames[i]+j);
                            for(int k=2;k<ClassIds.length+2;k++)
                                insert.setString(k,"");
                                int row=insert.executeUpdate();

                            }
                        }
                }
                catch(SQLException e){
                    e.printStackTrace();
                        }
        }

    }
    public void CreateTeachersRecordTable(){
        String TableName0=(Other.CourseName.getText()+"_"+Other.Branch.getText()+"_"+Other.Year.getText()+"_teachers_tt_record").toUpperCase();    
        String[] dayNames=new String[]{"Mo","Tu","We","Th","Fr","Sa","Su"};
        if(ClassIds.length>0){
            try{
                myCon=DriverManager.getConnection("jdbc:derby://localhost:1527/TTgen","rg","1234");
                myStat=myCon.createStatement();
                DatabaseMetaData dbm =myCon.getMetaData();
                ResultSet tables = dbm.getTables(null, null, TableName0, null);
                String query="create table "+TableName0+" (DAYS VARCHAR(10),";
                String query1="insert into "+TableName0+" values(?,";

                for(int k=0;k<ClassIds.length;k++){
                query=query+ClassIds[k]+" VARCHAR(100),";
                }
                query=query.substring(0, query.length()-1)+")";

                for(int k=0;k<ClassIds.length;k++){
                query1=query1+"?,";
                }
                query1=query1.substring(0, query1.length()-1)+")";


                if(!tables.next()){

                myStat=myCon.createStatement();
                myStat.executeUpdate(query);
                }

                for(int i=0;i<Days.getRowCount();i++){
                    for(int j=1;j<=8;j++){                    
                        PreparedStatement insert=(PreparedStatement) myCon.prepareStatement(query1);
                        insert.setString(1,dayNames[i]+j);
                    for(int k=2;k<ClassIds.length+2;k++)
                        insert.setString(k,"");
                        int row=insert.executeUpdate();

                    }
                }
            }
            catch(SQLException e){
                e.printStackTrace();
                    }
        }

    }
    public void CreateRoomsRecordTable(){
        String[] dayNames=new String[]{"Mo","Tu","We","Th","Fr","Sa","Su"};
        if(ClassIds.length>0){
            try{
                myCon=DriverManager.getConnection("jdbc:derby://localhost:1527/TTgen","rg","1234");
                myStat=myCon.createStatement();
                DatabaseMetaData dbm =myCon.getMetaData();
                ResultSet tables = dbm.getTables(null, null, TableName2, null);
                String query="create table "+TableName2+" (DAYS VARCHAR(10),";
                String query1="insert into "+TableName2+" values(?,";

                for(int k=0;k<ClassIds.length;k++){
                query=query+ClassIds[k]+" VARCHAR(100),";
                }
                query=query.substring(0, query.length()-1)+")";

                for(int k=0;k<ClassIds.length;k++){
                query1=query1+"?,";
                }
                query1=query1.substring(0, query1.length()-1)+")";


                if(!tables.next()){

                myStat=myCon.createStatement();
                myStat.executeUpdate(query);
                }

                for(int i=0;i<Days.getRowCount();i++){
                    for(int j=1;j<=8;j++){                    
                        PreparedStatement insert=(PreparedStatement) myCon.prepareStatement(query1);
                        insert.setString(1,dayNames[i]+j);
                    for(int k=2;k<ClassIds.length+2;k++)
                        insert.setString(k,"");
                        int row=insert.executeUpdate();

                    }
                }
            }
            catch(SQLException e){
                e.printStackTrace();
                    }
        }

    }
    public void DelRoomsRecord(){
        try{
            myCon=DriverManager.getConnection("jdbc:derby://localhost:1527/TTgen","rg","1234");
            myStat=myCon.createStatement();
            DatabaseMetaData dbm =myCon.getMetaData();
            ResultSet tables = dbm.getTables(null, null, TableName2, null);
           
                if(tables.next()){
                String query="drop table "+TableName2;       
                Statement delete=myCon.createStatement();
                delete.executeUpdate(query);
                }            
        }
        catch(SQLException e){
            e.printStackTrace();
                }
    
    
    }
    public void DelSubjectsRecord(){
        
        try{
            myCon=DriverManager.getConnection("jdbc:derby://localhost:1527/TTgen","rg","1234");
            myStat=myCon.createStatement();
            DatabaseMetaData dbm =myCon.getMetaData();
            ResultSet tables = dbm.getTables(null, null, TableName0, null);
           
                if(tables.next()){
                String query="drop table "+TableName0;       
                Statement delete=myCon.createStatement();
                delete.executeUpdate(query);
                }            
        }
        catch(SQLException e){
            e.printStackTrace();
                }
    
    
    }
    public void DelTeachersRecord(){        
        try{
            myCon=DriverManager.getConnection("jdbc:derby://localhost:1527/TTgen","rg","1234");
            myStat=myCon.createStatement();
            DatabaseMetaData dbm =myCon.getMetaData();
            ResultSet tables = dbm.getTables(null, null, TableName1, null);
           
                if(tables.next()){
                String query="drop table "+TableName1;       
                Statement delete=myCon.createStatement();
                delete.executeUpdate(query);
                }            
        }
        catch(SQLException e){
            e.printStackTrace();
                }
    
    
    }
    
    private void StudentPreviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentPreviewMouseClicked
    this.dispose();
    try{
        myCon=DriverManager.getConnection("jdbc:derby://localhost:1527/TTgen","rg","1234");
        myStat=myCon.createStatement();
        DatabaseMetaData dbm =myCon.getMetaData();
        ResultSet tables = dbm.getTables(null, null, TableName0, null);
        if(tables.next())
            DelSubjectsRecord();
    }
    catch(SQLException e){
            e.printStackTrace();
                }
    CreateSubjectsRecordTable();
    
    try{
        myCon=DriverManager.getConnection("jdbc:derby://localhost:1527/TTgen","rg","1234");
        myStat=myCon.createStatement();
        DatabaseMetaData dbm =myCon.getMetaData();
        ResultSet tables = dbm.getTables(null, null, TableName1, null);
        if(tables.next())
            DelTeachersRecord();
    }
    catch(SQLException e){
            e.printStackTrace();
                }
    CreateTeachersRecordTable();
    
    try{
        myCon=DriverManager.getConnection("jdbc:derby://localhost:1527/TTgen","rg","1234");
        myStat=myCon.createStatement();
        DatabaseMetaData dbm =myCon.getMetaData();
        ResultSet tables = dbm.getTables(null, null, TableName2, null);
        if(tables.next())
            DelRoomsRecord();
    }
    catch(SQLException e){
            e.printStackTrace();
                }
    CreateRoomsRecordTable();
    new StudentTtDetail().setVisible(true); 
    }//GEN-LAST:event_StudentPreviewMouseClicked

    private void TeacherPreviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeacherPreviewMouseClicked
    this.dispose();
    new TeacherTtDetail().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_TeacherPreviewMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About;
    private javax.swing.JButton Classes;
    private javax.swing.JButton Classrooms;
    private javax.swing.JButton DataView;
    private javax.swing.JButton GenerateTT;
    private javax.swing.JButton Help;
    private javax.swing.JButton LogOrReg;
    private javax.swing.JButton OtherInfo;
    private javax.swing.JButton Settings2;
    private javax.swing.JButton StudentPreview;
    private javax.swing.JButton Subjects;
    private javax.swing.JButton TeacherPreview;
    private javax.swing.JButton Teachers;
    private javax.swing.JButton User;
    public static final javax.swing.JTextField WelInfo = new javax.swing.JTextField();
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel set1;
    private javax.swing.JLabel set2;
    private javax.swing.JPanel viewpane;
    private javax.swing.JLabel viewsetting;
    // End of variables declaration//GEN-END:variables
}
