/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TTgen0;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ragha
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    Connection myCon=null;
    Statement myStat=null;
    ResultSet myResult=null;
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cross = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        Show = new javax.swing.JLabel();
        Hide = new javax.swing.JLabel();
        ForgotPass = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        AddNew = new javax.swing.JLabel();
        TnC = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cross.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Cross.setForeground(new java.awt.Color(255, 255, 255));
        Cross.setText("X");
        Cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrossMouseClicked(evt);
            }
        });
        jPanel1.add(Cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 35, 20, 30));

        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(null);
        email.setCaretColor(new java.awt.Color(255, 255, 255));
        email.setOpaque(false);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 220, 20));

        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(null);
        password.setCaretColor(new java.awt.Color(255, 255, 255));
        password.setOpaque(false);
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 272, 200, 20));

        Show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowMouseClicked(evt);
            }
        });
        jPanel1.add(Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 20, 20));

        Hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HideMouseClicked(evt);
            }
        });
        jPanel1.add(Hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 20, 20));

        ForgotPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgotPassMouseClicked(evt);
            }
        });
        jPanel1.add(ForgotPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 304, 110, 20));

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 350, 110, 30));

        AddNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNewMouseClicked(evt);
            }
        });
        jPanel1.add(AddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 458, 30, 30));
        jPanel1.add(TnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 485, 120, 15));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login2.jpg"))); // NOI18N
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 900, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CrossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrossMouseClicked
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_CrossMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        String query1="SELECT * FROM LogData where Email = '"+email.getText()+"' and password = '"+password.getText()+"'";
     //   String query2="CREATE table abcd (Name Varchar(100))";
        
        try{
            myCon=DriverManager.getConnection("jdbc:derby://localhost:1527/TTgen","rg","1234");
            myStat=myCon.createStatement();
            myResult=myStat.executeQuery(query1);
            if(myResult.next())
            {
            String uname=myResult.getString("Username");
        
            this.dispose();
            Dashboard.WelInfo.setText("Welcome "+uname);
            new Dashboard().setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Invalid email or password.");
            }
        
        } 
        catch(SQLException e){
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void AddNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewMouseClicked
this.dispose();
new SignupPage().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AddNewMouseClicked

    private void ShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseClicked
    Hide.setVisible(true);
    Hide.setEnabled(true);
    password.setEchoChar((char)0);
    ImageIcon A= new ImageIcon(getClass().getResource("/img/login.jpg"));
    BG.setIcon(A);
    Show.setVisible(false);
    Show.setEnabled(false);    // TODO add your handling code here:
    }//GEN-LAST:event_ShowMouseClicked

    private void HideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HideMouseClicked
    Show.setVisible(true);
    Show.setEnabled(true);
    password.setEchoChar((char)8226);
    ImageIcon A= new ImageIcon(getClass().getResource("/img/login2.jpg"));
    BG.setIcon(A);
    Hide.setVisible(false);
    Hide.setEnabled(false);// TODO add your handling code here:
            // TODO add your handling code here:
    }//GEN-LAST:event_HideMouseClicked

    private void ForgotPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgotPassMouseClicked
            // TODO add your handling code here:
    }//GEN-LAST:event_ForgotPassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddNew;
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Cross;
    private javax.swing.JLabel ForgotPass;
    private javax.swing.JLabel Hide;
    private javax.swing.JLabel Show;
    private javax.swing.JLabel TnC;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
