/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TTgen0;

import java.awt.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFileChooser;
import java.io.*;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import java.util.*;
import static TTgen0.ClassesDatabase.ClassesLoadTable;



/**
 *
 * @author 91870
 */


public class Other extends javax.swing.JFrame {
    

    /**
     * Creates new form Other
     */
    Connection myCon=null;
    Statement myStat=null;
    ResultSet myResult=null;
    int i,j,k,l;
    public static int sHour=8,sMin=45,eHour=4,eMin=4;
    public static String sAmpm="AM",eAmpm="PM";
    public static int[] Available=new int[0];
    public static int[] CombinedAvailable=new int[0];
    public static int rownum;
    
    public void AddAvailable(){
    
         rownum = Days.getRowCount();
         Available=new int[rownum*8];
         CombinedAvailable=new int[Integer.parseInt(CombinedClasses.getText())]; 

        
        DefaultTableModel model = (DefaultTableModel) Days.getModel();
            j=0;
        for(i=0;i<rownum;i++){
            String DayName = model.getValueAt(i, 0).toString();
            
            if(DayName.equals("Monday")){l=1;for(k=1;k<=8;k++,j++,l++){Available[j]=l;}}
            if(DayName.equals("Tuesday")){l=9;for(k=1;k<=8;k++,j++,l++){Available[j]=l;}}
            if(DayName.equals("Wednesday")){l=17;for(k=1;k<=8;k++,j++,l++){Available[j]=l;}}
            if(DayName.equals("Thursday")){l=25;for(k=1;k<=8;k++,j++,l++){Available[j]=l;}}
            if(DayName.equals("Friday")){l=33;for(k=1;k<=8;k++,j++,l++){Available[j]=l;}}
            if(DayName.equals("Saturday")){l=41;for(k=1;k<=8;k++,j++,l++){Available[j]=l;}}
            if(DayName.equals("Sunday")){l=49;for(k=1;k<=8;k++,j++,l++){Available[j]=l;}}              
        }
        
       
                
                for(i=0;i<CombinedAvailable.length;i++){CombinedAvailable[i]=Available[i];}
    }
    
    

    
    public Other() {
        initComponents();
        
      //  NoOfClasses.setModel(new DefaultComboBoxModel<>(new String[] {"Select"}));
      //  BreakTime.setModel(new DefaultComboBoxModel<>(new String[] {"Select"}));
        Mon1.setVisible(false);
        Tue1.setVisible(false);
        Wed1.setVisible(false);
        Thu1.setVisible(false);
        Fri1.setVisible(false);
        Sat1.setVisible(false);
        Sun1.setVisible(false);
        Mon1.setEnabled(false);
        Tue1.setEnabled(false);
        Wed1.setEnabled(false);
        Thu1.setEnabled(false);
        Fri1.setEnabled(false);
        Sat1.setEnabled(false);
        Sun1.setEnabled(false);
        Clock1.setEnabled(false);
        Clock1.setVisible(false);
        DefaultTableModel model = (DefaultTableModel) Days.getModel();
        model.addRow(new Object[]{"Monday"});
        model.addRow(new Object[]{"Tuesday"});
        model.addRow(new Object[]{"Wednesday"});
        model.addRow(new Object[]{"Thursday"});
        model.addRow(new Object[]{"Friday"});
        AddAvailable();
        


        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cross = new javax.swing.JLabel();
        InstituteName = new javax.swing.JTextField();
        View = new javax.swing.JLabel();
        Upload = new javax.swing.JLabel();
        CourseName = new javax.swing.JTextField();
        Branch = new javax.swing.JTextField();
        Year = new javax.swing.JTextField();
        CC = new javax.swing.JLabel();
        CombinedClasses = new javax.swing.JTextField();
        StartTime = new javax.swing.JTextField();
        EndTime = new javax.swing.JTextField();
        Clock1 = new javax.swing.JPanel();
        Hour = new javax.swing.JTextField();
        HUp = new javax.swing.JLabel();
        HDown = new javax.swing.JLabel();
        HUpDown = new javax.swing.JLabel();
        Minutes = new javax.swing.JTextField();
        MUp = new javax.swing.JLabel();
        MDown = new javax.swing.JLabel();
        MUpDown = new javax.swing.JLabel();
        AmPm = new javax.swing.JComboBox<>();
        Tick1 = new javax.swing.JLabel();
        Tick2 = new javax.swing.JLabel();
        NoOfClasses = new javax.swing.JComboBox<>();
        BreakTime = new javax.swing.JComboBox<>();
        IncludeInterval = new javax.swing.JCheckBox();
        Add = new javax.swing.JLabel();
        Remove = new javax.swing.JButton();
        Apply = new javax.swing.JLabel();
        Cancel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Days = new javax.swing.JTable();
        Mon = new javax.swing.JLabel();
        Tue = new javax.swing.JLabel();
        Wed = new javax.swing.JLabel();
        Thu = new javax.swing.JLabel();
        Fri = new javax.swing.JLabel();
        Sat = new javax.swing.JLabel();
        Sun = new javax.swing.JLabel();
        Mon1 = new javax.swing.JLabel();
        Tue1 = new javax.swing.JLabel();
        Wed1 = new javax.swing.JLabel();
        Thu1 = new javax.swing.JLabel();
        Fri1 = new javax.swing.JLabel();
        Sat1 = new javax.swing.JLabel();
        Sun1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrossMouseClicked(evt);
            }
        });
        jPanel1.add(Cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 10, 20, 20));

        InstituteName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        InstituteName.setText("SHARDA UNIVERSITY");
        InstituteName.setBorder(null);
        InstituteName.setOpaque(false);
        InstituteName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstituteNameActionPerformed(evt);
            }
        });
        jPanel1.add(InstituteName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 68, 215, 18));

        View.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        View.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewMouseClicked(evt);
            }
        });
        jPanel1.add(View, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 66, 25, 25));

        Upload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Upload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UploadMouseClicked(evt);
            }
        });
        jPanel1.add(Upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 66, 24, 25));

        CourseName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CourseName.setText("BTech");
        CourseName.setBorder(null);
        CourseName.setOpaque(false);
        CourseName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CourseNameMouseClicked(evt);
            }
        });
        jPanel1.add(CourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 313, 303, 18));

        Branch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Branch.setText("CSE");
        Branch.setBorder(null);
        Branch.setOpaque(false);
        jPanel1.add(Branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 339, 303, 18));

        Year.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Year.setText("2");
        jPanel1.add(Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 433, 80, 23));

        CC.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        CC.setText("Combined Classes");
        jPanel1.add(CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 430, 93, 30));

        CombinedClasses.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        CombinedClasses.setText("3");
        jPanel1.add(CombinedClasses, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 433, 80, 23));

        StartTime.setEditable(false);
        StartTime.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        StartTime.setText("8:45 AM");
        StartTime.setBorder(null);
        StartTime.setOpaque(false);
        StartTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartTimeMouseClicked(evt);
            }
        });
        jPanel1.add(StartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 364, 75, 18));

        EndTime.setEditable(false);
        EndTime.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        EndTime.setText("4:00 PM");
        EndTime.setBorder(null);
        EndTime.setOpaque(false);
        EndTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EndTimeMouseClicked(evt);
            }
        });
        jPanel1.add(EndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 364, 75, 18));

        Clock1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hour.setEditable(false);
        Hour.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Hour.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Hour.setText("8");
        Clock1.add(Hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 35, 20));

        HUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HUpMouseClicked(evt);
            }
        });
        Clock1.add(HUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 0, 15, 10));

        HDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HDownMouseClicked(evt);
            }
        });
        Clock1.add(HDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 10, 15, 10));

        HUpDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UpDown.png"))); // NOI18N
        Clock1.add(HUpDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 0, 15, 20));

        Minutes.setEditable(false);
        Minutes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Minutes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Minutes.setText("00");
        Clock1.add(Minutes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 35, 20));

        MUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MUpMouseClicked(evt);
            }
        });
        Clock1.add(MUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, 15, 10));

        MDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MDownMouseClicked(evt);
            }
        });
        Clock1.add(MDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 10, 15, 10));

        MUpDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UpDown.png"))); // NOI18N
        Clock1.add(MUpDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 0, 15, 20));

        AmPm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AmPm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        Clock1.add(AmPm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 43, 20));

        Tick1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tick1.setText("✔");
        Tick1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tick1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tick1MouseClicked(evt);
            }
        });
        Clock1.add(Tick1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 0, 15, 20));

        Tick2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tick2.setText("✔");
        Tick2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tick2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tick2MouseClicked(evt);
            }
        });
        Clock1.add(Tick2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 0, 15, 20));

        jPanel1.add(Clock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 364, -1, -1));

        NoOfClasses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NoOfClasses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "5", "6", "7", "8" }));
        NoOfClasses.setSelectedIndex(4);
        NoOfClasses.setSelectedItem(8);
        jPanel1.add(NoOfClasses, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 398, 80, 19));

        BreakTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BreakTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "15" }));
        jPanel1.add(BreakTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 398, 50, 19));

        IncludeInterval.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        IncludeInterval.setText("Include Interval");
        IncludeInterval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncludeIntervalActionPerformed(evt);
            }
        });
        jPanel1.add(IncludeInterval, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 465, 20, -1));

        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 215, 49, 18));

        Remove.setBackground(new java.awt.Color(255, 255, 255));
        Remove.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        Remove.setBorderPainted(false);
        Remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Remove.setOpaque(false);
        Remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RemoveMouseClicked(evt);
            }
        });
        jPanel1.add(Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 247, 49, 20));

        Apply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Apply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ApplyMouseClicked(evt);
            }
        });
        jPanel1.add(Apply, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 514, 59, 18));

        Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 514, 59, 18));

        Days.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Days);
        if (Days.getColumnModel().getColumnCount() > 0) {
            Days.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 122, 148, 149));

        Mon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Mon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mon.setText("Monday");
        Mon.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Mon.setName(""); // NOI18N
        Mon.setOpaque(true);
        Mon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MonMouseClicked(evt);
            }
        });
        jPanel1.add(Mon, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 130, 148, 20));

        Tue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tue.setText("Tuesday");
        Tue.setOpaque(true);
        Tue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TueMouseClicked(evt);
            }
        });
        jPanel1.add(Tue, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 150, 148, 20));

        Wed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Wed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Wed.setText("Wednesday");
        Wed.setOpaque(true);
        Wed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WedMouseClicked(evt);
            }
        });
        jPanel1.add(Wed, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 170, 148, 20));

        Thu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Thu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Thu.setText("Thursday");
        Thu.setOpaque(true);
        Thu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThuMouseClicked(evt);
            }
        });
        jPanel1.add(Thu, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 190, 148, 20));

        Fri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fri.setText("Friday");
        Fri.setOpaque(true);
        Fri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FriMouseClicked(evt);
            }
        });
        jPanel1.add(Fri, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 210, 148, 20));

        Sat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Sat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sat.setText("Saturday");
        Sat.setOpaque(true);
        Sat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SatMouseClicked(evt);
            }
        });
        jPanel1.add(Sat, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 230, 148, 20));

        Sun.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Sun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sun.setText("Sunday");
        Sun.setOpaque(true);
        Sun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SunMouseClicked(evt);
            }
        });
        jPanel1.add(Sun, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 250, 148, 20));

        Mon1.setBackground(new java.awt.Color(51, 153, 255));
        Mon1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Mon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mon1.setText("Monday");
        Mon1.setName(""); // NOI18N
        Mon1.setOpaque(true);
        Mon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Mon1MouseClicked(evt);
            }
        });
        jPanel1.add(Mon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 130, 148, 20));

        Tue1.setBackground(new java.awt.Color(51, 153, 255));
        Tue1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tue1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tue1.setText("Tuesday");
        Tue1.setOpaque(true);
        Tue1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tue1MouseClicked(evt);
            }
        });
        jPanel1.add(Tue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 150, 148, 20));

        Wed1.setBackground(new java.awt.Color(51, 153, 255));
        Wed1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Wed1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Wed1.setText("Wednesday");
        Wed1.setOpaque(true);
        Wed1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Wed1MouseClicked(evt);
            }
        });
        jPanel1.add(Wed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 170, 148, 20));

        Thu1.setBackground(new java.awt.Color(51, 153, 255));
        Thu1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Thu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Thu1.setText("Thursday");
        Thu1.setOpaque(true);
        Thu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Thu1MouseClicked(evt);
            }
        });
        jPanel1.add(Thu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 190, 148, 20));

        Fri1.setBackground(new java.awt.Color(51, 153, 255));
        Fri1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fri1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fri1.setText("Friday");
        Fri1.setOpaque(true);
        Fri1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Fri1MouseClicked(evt);
            }
        });
        jPanel1.add(Fri1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 210, 148, 20));

        Sat1.setBackground(new java.awt.Color(51, 153, 255));
        Sat1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Sat1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sat1.setText("Saturday");
        Sat1.setOpaque(true);
        Sat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sat1MouseClicked(evt);
            }
        });
        jPanel1.add(Sat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 230, 148, 20));

        Sun1.setBackground(new java.awt.Color(51, 153, 255));
        Sun1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Sun1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sun1.setText("Sunday");
        Sun1.setOpaque(true);
        Sun1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sun1MouseClicked(evt);
            }
        });
        jPanel1.add(Sun1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 250, 148, 20));

        jLabel2.setText("MIN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 398, 23, 19));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/other.jpg"))); // NOI18N
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IncludeIntervalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncludeIntervalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IncludeIntervalActionPerformed

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
                                           
    DefaultTableModel model = (DefaultTableModel) Days.getModel();
    model.setRowCount(0);
    if(Mon1.isEnabled())
    {
    model.addRow(new Object[]{Mon1.getText()});
    }
    if(Tue1.isEnabled())
    {
    model.addRow(new Object[]{Tue1.getText()});
    }
    if(Wed1.isEnabled())
    {
    model.addRow(new Object[]{Wed1.getText()});
    }
    if(Thu1.isEnabled())
    {
    model.addRow(new Object[]{Thu1.getText()});
    }
    if(Fri1.isEnabled())
    {
    model.addRow(new Object[]{Fri1.getText()});
    }
    if(Sat1.isEnabled())
    {
    model.addRow(new Object[]{Sat1.getText()});
    }
    if(Sun1.isEnabled())
    {
    model.addRow(new Object[]{Sun1.getText()});
    }
        Mon1.setVisible(false);
        Tue1.setVisible(false);
        Wed1.setVisible(false);
        Thu1.setVisible(false);
        Fri1.setVisible(false);
        Sat1.setVisible(false);
        Sun1.setVisible(false);
        
        Mon.setVisible(true);Mon.setEnabled(true);
        Tue.setVisible(true);Tue.setEnabled(true);
        Wed.setVisible(true);Wed.setEnabled(true);
        Thu.setVisible(true);Thu.setEnabled(true);
        Fri.setVisible(true);Fri.setEnabled(true);
        Sat.setVisible(true);Sat.setEnabled(true);
        Sun.setVisible(true);Sun.setEnabled(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_AddMouseClicked

    private void MonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MonMouseClicked
    Mon.setVisible(false);
    Mon.setEnabled(false);
    Mon1.setVisible(true);
    Mon1.setEnabled(true);
    }//GEN-LAST:event_MonMouseClicked

    private void Mon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mon1MouseClicked
    Mon1.setVisible(false);
    Mon1.setEnabled(false);
    Mon.setVisible(true);
    Mon.setEnabled(true);
    }//GEN-LAST:event_Mon1MouseClicked

    private void TueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TueMouseClicked
    Tue.setVisible(false);
    Tue.setEnabled(false);
    Tue1.setVisible(true);
    Tue1.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_TueMouseClicked

    private void Tue1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tue1MouseClicked
    Tue1.setVisible(false);
    Tue1.setEnabled(false);
    Tue.setVisible(true);
    Tue.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_Tue1MouseClicked

    private void WedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WedMouseClicked
    Wed.setVisible(false);
    Wed.setEnabled(false);
    Wed1.setVisible(true);
    Wed1.setEnabled(true);    // TODO add your handling code here:
    // TODO add your handling code here:
    }//GEN-LAST:event_WedMouseClicked

    private void ThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThuMouseClicked
    Thu.setVisible(false);
    Thu.setEnabled(false);
    Thu1.setVisible(true);
    Thu1.setEnabled(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_ThuMouseClicked

    private void FriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FriMouseClicked
    Fri.setVisible(false);
    Fri.setEnabled(false);
    Fri1.setVisible(true);
    Fri1.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_FriMouseClicked

    private void SatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SatMouseClicked
    Sat.setVisible(false);
    Sat.setEnabled(false);
    Sat1.setVisible(true); 
    Sat1.setEnabled(true);        // TODO add your handling code here:
    // TODO add your handling code here:
    }//GEN-LAST:event_SatMouseClicked

    private void SunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SunMouseClicked
    Sun.setVisible(false);
    Sun.setEnabled(false);
    Sun1.setVisible(true);
    Sun1.setEnabled(true);        // TODO add your handling code here:
    // TODO add your handling code here:
    }//GEN-LAST:event_SunMouseClicked

    private void Wed1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Wed1MouseClicked
    Wed1.setVisible(false);
    Wed1.setEnabled(false);
    Wed.setVisible(true);
    Wed.setEnabled(true);    // TODO add your handling code here:
    }//GEN-LAST:event_Wed1MouseClicked

    private void Thu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Thu1MouseClicked
    Thu1.setVisible(false);
    Thu1.setEnabled(false);
    Thu.setVisible(true);
    Thu.setEnabled(true);
// TODO add your handling code here:
    }//GEN-LAST:event_Thu1MouseClicked

    private void Fri1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fri1MouseClicked
    Fri1.setVisible(false);
    Fri1.setEnabled(false);
    Fri.setVisible(true);
    Fri.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_Fri1MouseClicked

    private void Sat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sat1MouseClicked
    Sat1.setVisible(false);
    Sat1.setEnabled(false);
    Sat.setVisible(true);
    Sat.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_Sat1MouseClicked

    private void Sun1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sun1MouseClicked
    Sun1.setVisible(false);
    Sun1.setEnabled(false);
    Sun.setVisible(true);
    Sun.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_Sun1MouseClicked

    private void RemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveMouseClicked
    int[] rownum = Days.getSelectedRows();
    DefaultTableModel model = (DefaultTableModel) Days.getModel();
    if(rownum.length >0){
        for(int i=0;i<rownum.length;i++){
            String DayName = model.getValueAt(rownum[i], 0).toString();
            model.removeRow(rownum[i]);
            
            if(DayName.equals("Monday")){Mon1.setEnabled(false);}
            if(DayName.equals("Tuesday")){Tue1.setEnabled(false);}
            if(DayName.equals("Wednesday")){Wed1.setEnabled(false);}
            if(DayName.equals("Thursday")){Thu1.setEnabled(false);}
            if(DayName.equals("Friday")){Fri1.setEnabled(false);}
            if(DayName.equals("Saturday")){Sat1.setEnabled(false);}
            if(DayName.equals("Sunday")){Sun1.setEnabled(false);}              
        }
    }
    else
    {
    JOptionPane.showMessageDialog(null,"Unable to Remove");
    }
// TODO add your handling code here:
    }//GEN-LAST:event_RemoveMouseClicked

    private void CrossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrossMouseClicked
        this.dispose();
        new Dashboard().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_CrossMouseClicked

    private void HUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HUpMouseClicked
/*   if(!("").equals(StartTime.getText())){
       if((AmPm.getSelectedItem().toString()).equals(sAmpm)){
           System.out.println("done");
           if((Integer.parseInt(Hour.getText()) + 1)>0 && (Integer.parseInt(Hour.getText()) + 1)<13 && (Integer.parseInt(Hour.getText()) )> sHour){
        Hour.setText(Integer.toString(Integer.parseInt(Hour.getText()) + 1));}
            else{
        HUp.setEnabled(false);} 
       }
    }                   */
        if((Integer.parseInt(Hour.getText()) + 1)>0 && (Integer.parseInt(Hour.getText()) + 1)<13){
        Hour.setText(Integer.toString(Integer.parseInt(Hour.getText()) + 1));}
    else{
    HUp.setEnabled(false);}// TODO add your handling code here:
    
    }//GEN-LAST:event_HUpMouseClicked

    private void HDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HDownMouseClicked
    if((Integer.parseInt(Hour.getText()) - 1)>0 && (Integer.parseInt(Hour.getText()) - 1)<13){
        Hour.setText(Integer.toString(Integer.parseInt(Hour.getText()) - 1));}
    else{
    HDown.setEnabled(false);}// TODO add your handling code here:
    }//GEN-LAST:event_HDownMouseClicked

    private void MUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MUpMouseClicked
    if((Integer.parseInt(Minutes.getText()) + 5)>=0 && (Integer.parseInt(Minutes.getText()) + 5)<=55){
        if((Integer.toString(Integer.parseInt(Minutes.getText()) + 5).length()==1)){
        Minutes.setText("0"+Integer.toString(Integer.parseInt(Minutes.getText()) + 5));}
        else{       
        Minutes.setText(   Integer.toString(Integer.parseInt(Minutes.getText()) + 5)   );}} 
    else{
    MUp.setEnabled(false);}// TODO add your handling code here:
    }//GEN-LAST:event_MUpMouseClicked

    private void MDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MDownMouseClicked
    if((Integer.parseInt(Minutes.getText()) - 5)>=0 && (Integer.parseInt(Minutes.getText()) - 5)<=55){
        if((Integer.toString(Integer.parseInt(Minutes.getText()) - 5).length()==1)){
        Minutes.setText("0"+Integer.toString(Integer.parseInt(Minutes.getText()) - 5));}
        else{
        Minutes.setText(Integer.toString(Integer.parseInt(Minutes.getText()) - 5)); }}
    else{
    MDown.setEnabled(false);}// TODO add your handling code here:
    }//GEN-LAST:event_MDownMouseClicked

    private void StartTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartTimeMouseClicked
        StartTime.setEnabled(false);
        StartTime.setVisible(false);
        Clock1.setEnabled(true);
        Clock1.setVisible(true);
        Tick2.setVisible(false);
        Tick2.setEnabled(false);
        Tick1.setVisible(true);
        Tick1.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_StartTimeMouseClicked

    private void Tick2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tick2MouseClicked
        Clock1.setEnabled(false);
        Clock1.setVisible(false);
        Tick2.setVisible(false);
        Tick2.setEnabled(false);
        Tick1.setVisible(true);
        Tick1.setEnabled(true);
        StartTime.setEnabled(true);
        StartTime.setVisible(true);
        EndTime.setEnabled(true);
        EndTime.setVisible(true);
        String ampm=AmPm.getSelectedItem().toString();
        if(Minutes.getText().length()==1){
        EndTime.setText(Hour.getText()+":0"+Minutes.getText()+" "+ampm);}
        else{
        EndTime.setText(Hour.getText()+":"+Minutes.getText()+" "+ampm);}
        eHour=Integer.parseInt(Hour.getText());
        eMin=Integer.parseInt(Minutes.getText());
        eAmpm=ampm;     // TODO add your handling code here:
    }//GEN-LAST:event_Tick2MouseClicked

    private void EndTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EndTimeMouseClicked
        EndTime.setEnabled(false);
        EndTime.setVisible(false);
        Clock1.setEnabled(true);
        Clock1.setVisible(true);
        Tick1.setVisible(false);
        Tick1.setEnabled(false);
        Tick2.setVisible(true);
        Tick2.setEnabled(true);
                // TODO add your handling code here:
    }//GEN-LAST:event_EndTimeMouseClicked

    private void Tick1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tick1MouseClicked
        Clock1.setEnabled(false);
        Clock1.setVisible(false);
        Tick1.setVisible(false);
        Tick1.setEnabled(false);
        Tick2.setVisible(true);
        Tick2.setEnabled(true);
        StartTime.setEnabled(true);
        StartTime.setVisible(true);
        EndTime.setEnabled(true);
        EndTime.setVisible(true);
        String ampm=(String) AmPm.getSelectedItem();
        if(Minutes.getText().length()==1){
        StartTime.setText(Hour.getText()+":0"+Minutes.getText()+" "+ampm);}
        else{
        StartTime.setText(Hour.getText()+":"+Minutes.getText()+" "+ampm);}
        sHour=Integer.parseInt(Hour.getText());
        sMin=Integer.parseInt(Minutes.getText());
        sAmpm=ampm;
        //System.out.println(sHour+" "+sMin+" "+sAmpm);
        

// TODO add your handling code here:
    }//GEN-LAST:event_Tick1MouseClicked

    private void ApplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApplyMouseClicked
   // ClassSub cs = new ClassSub();
    //ClassesDatabase cd = new ClassesDatabase();
   // RoomsDatabase rd = new RoomsDatabase();
   // SubjectsDatabase sd = new SubjectsDatabase();
    //TeachersDatabase td = new TeachersDatabase();
    int rownum = Days.getRowCount();
    if(rownum==0)
    {    JOptionPane.showMessageDialog(null,"Add Days");
        }else{
    AddAvailable();
    this.dispose();
    
    new Dashboard().setVisible(true);}
    // TODO add your handling code here:
    }//GEN-LAST:event_ApplyMouseClicked

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
    InstituteName.setText(null);
    CourseName.setText(null);
    Branch.setText(null);
    StartTime.setText(null);
    EndTime.setText(null);
    this.dispose();
    new Dashboard().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_CancelMouseClicked

    private void CourseNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseNameMouseClicked

    private void UploadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UploadMouseClicked
    JFileChooser fileChooser = new JFileChooser();
    //fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
    File selectedFile = fileChooser.getSelectedFile();
    
    try{
    myCon=DriverManager.getConnection("jdbc:derby://localhost:1527/TTgen","rg","1234");
    myStat=myCon.createStatement();
    
    String query="select NAME from LOGOS where name='"+InstituteName.getText().toUpperCase()+"'";       
    //PreparedStatement select=myCon.prepareStatement(query);
    ResultSet rs1 =myStat.executeQuery(query);
    if(rs1.next()){
        String query1="delete from LOGOS where NAME ='"+InstituteName.getText().toUpperCase()+"'";       
        Statement delete=myCon.createStatement();
        delete.executeUpdate(query1);       
    }
    
   
    FileInputStream fin = new FileInputStream(selectedFile);
    PreparedStatement pre = myCon.prepareStatement("insert into LOGOS values(?,?)");
    pre.setString(1,InstituteName.getText().toUpperCase());
    pre.setBinaryStream(2,(InputStream)fin,(int)selectedFile.length());
    pre.executeUpdate();
    }
    catch(SQLException e){
        e.printStackTrace();
    }   catch (FileNotFoundException ex) {
            Logger.getLogger(Other.class.getName()).log(Level.SEVERE, null, ex);
        }   catch(NullPointerException e){
            }
    
}
        // TODO add your handling code here:
    }//GEN-LAST:event_UploadMouseClicked

    private void ViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewMouseClicked
    byte[] imageBytes;
    Image image;
    String IName=InstituteName.getText().toUpperCase();
    try{
    myCon=DriverManager.getConnection("jdbc:derby://localhost:1527/TTgen","rg","1234");
    myStat=myCon.createStatement();
    
    PreparedStatement pre = myCon.prepareStatement("select IMG from LOGOS where NAME='"+IName+"'");
    ResultSet rs2 =pre.executeQuery();
    while(rs2.next())
    {
    imageBytes=rs2.getBytes(1);
    image=getToolkit().createImage(imageBytes);
    ImageIcon icon= new ImageIcon(image);
    new ViewLogo().setVisible(true);
    ViewLogo.Img.setIcon(icon);}
    }
    
    
    catch(Exception ex){
        System.out.println(ex.getMessage());
    }
            // TODO add your handling code here:
    }//GEN-LAST:event_ViewMouseClicked

    private void InstituteNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstituteNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InstituteNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Other.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Other.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Other.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Other.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Other().setVisible(true);
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JComboBox<String> AmPm;
    private javax.swing.JLabel Apply;
    private javax.swing.JLabel BG;
    public static javax.swing.JTextField Branch;
    public static javax.swing.JComboBox<String> BreakTime;
    private javax.swing.JLabel CC;
    private javax.swing.JLabel Cancel;
    private javax.swing.JPanel Clock1;
    public static javax.swing.JTextField CombinedClasses;
    public static javax.swing.JTextField CourseName;
    private javax.swing.JLabel Cross;
    public static javax.swing.JTable Days;
    private javax.swing.JTextField EndTime;
    private javax.swing.JLabel Fri;
    private javax.swing.JLabel Fri1;
    private javax.swing.JLabel HDown;
    private javax.swing.JLabel HUp;
    private javax.swing.JLabel HUpDown;
    private javax.swing.JTextField Hour;
    private javax.swing.JCheckBox IncludeInterval;
    public static javax.swing.JTextField InstituteName;
    private javax.swing.JLabel MDown;
    private javax.swing.JLabel MUp;
    private javax.swing.JLabel MUpDown;
    private javax.swing.JTextField Minutes;
    private javax.swing.JLabel Mon;
    private javax.swing.JLabel Mon1;
    public static javax.swing.JComboBox<String> NoOfClasses;
    private javax.swing.JButton Remove;
    private javax.swing.JLabel Sat;
    private javax.swing.JLabel Sat1;
    private javax.swing.JTextField StartTime;
    private javax.swing.JLabel Sun;
    private javax.swing.JLabel Sun1;
    private javax.swing.JLabel Thu;
    private javax.swing.JLabel Thu1;
    private javax.swing.JLabel Tick1;
    private javax.swing.JLabel Tick2;
    private javax.swing.JLabel Tue;
    private javax.swing.JLabel Tue1;
    private javax.swing.JLabel Upload;
    private javax.swing.JLabel View;
    private javax.swing.JLabel Wed;
    private javax.swing.JLabel Wed1;
    public static javax.swing.JTextField Year;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
