/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TTgen0;

import static TTgen0.ClassesDatabase.ClassIds;
import static TTgen0.Other.Days;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author 91870
 */
public class RoomsDatabase extends javax.swing.JFrame {

    /**
     * Creates new form TeachersDatabase
     */
    Connection myCon=null;
    Statement myStat=null;
    ResultSet myResult=null;
    int i=0;
    
    String TableName;

    
    public RoomsDatabase() {
        initComponents();
        try{
        TableName=(Other.CourseName.getText()+"_"+Other.Branch.getText()+"_"+Other.Year.getText()+"_Rooms").toUpperCase();}
        catch(NullPointerException e){
        TableName="btech_cse_1_rooms".toUpperCase();
        }
        ViewData();        
    }
    
    public void ViewData()
    {
       try{
        myCon=DriverManager.getConnection("jdbc:derby://localhost:1527/TTgen","rg","1234");
        myStat=myCon.createStatement();
        DatabaseMetaData dbm = myCon.getMetaData();
        ResultSet tables = dbm.getTables(null, null,TableName,null);
        if(tables.next())
        {
        myResult=myStat.executeQuery("Select * from "+TableName);
        RoomsTable.setModel(DbUtils.resultSetToTableModel(myResult));      
        }
        
        else
        {
        DefaultTableModel dm = (DefaultTableModel) RoomsTable.getModel();
        dm.setRowCount(0);}
        
        }

    catch(SQLException e){
            e.printStackTrace();
                }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RoomsTable = new javax.swing.JTable();
        RoomName = new javax.swing.JTextField();
        RoomId = new javax.swing.JTextField();
        Delete = new javax.swing.JLabel();
        Edit = new javax.swing.JLabel();
        Add = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RoomsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "RoomName", "Room Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(RoomsTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 760, 320));

        RoomName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RoomName.setForeground(new java.awt.Color(255, 255, 255));
        RoomName.setBorder(null);
        RoomName.setOpaque(false);
        jPanel1.add(RoomName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 220, 30));
        RoomName.getAccessibleContext().setAccessibleName("TextName");

        RoomId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RoomId.setForeground(new java.awt.Color(255, 255, 255));
        RoomId.setBorder(null);
        RoomId.setOpaque(false);
        jPanel1.add(RoomId, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 90, 30));

        Delete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Delete.setText("Delete");
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 478, 129, 30));

        Edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditMouseClicked(evt);
            }
        });
        jPanel1.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 478, 126, 32));

        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 478, 127, 30));

        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 478, 126, 30));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RoomsDatabse.png"))); // NOI18N
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("StaffDatabaseFrame");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        this.dispose();
        new Dashboard().setVisible(true);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_BackMouseClicked
        
    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
    if("".equals(RoomId.getText()))
        {JOptionPane.showMessageDialog(this, "ENTER ROOM ID","Error",JOptionPane.WARNING_MESSAGE);}
    else{    
    try{
        String query="DELETE from "+TableName+" where roomid ='"+RoomId.getText()+"'";
        Statement add=myCon.createStatement();
        add.executeUpdate(query);
        RoomId.setText("");
    }                                   
   catch(SQLException e)
        {
            e.printStackTrace();
        }
    ViewData();   
    }// TODO add your handling code here:
    }//GEN-LAST:event_DeleteMouseClicked

    private void EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseClicked
    if("".equals(RoomId.getText()))
    {
    JOptionPane.showMessageDialog(this, "ENTER ROOM ID","Error",JOptionPane.WARNING_MESSAGE);}
    else{   
    
        try{
        String query="update "+TableName+" set roomname ='"+RoomName.getText()+"' "+",roomid='"+RoomId.getText()+"'where roomid ='"+RoomId.getText()+"'";       
        Statement update=myCon.createStatement();
        update.executeUpdate(query);
        RoomId.setText("");
        RoomName.setText("");
    }                                   
   catch(SQLException e)
        {
            e.printStackTrace();
        }
    ViewData();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_EditMouseClicked

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
    if("".equals(RoomName.getText())||"".equals(RoomId.getText()))
    {JOptionPane.showMessageDialog(this, "ENTER COPLETE DATA","Error",JOptionPane.WARNING_MESSAGE);
    }
    else{
        try{
            String query="Insert into "+TableName+" values(?,?)";
            String q1="Create table "+TableName+" (RoomName Varchar(100) ,RoomId Varchar(100))";
            String TName2=(Other.CourseName.getText()+"_"+Other.Branch.getText()+"_"+Other.Year.getText()+"_availablerooms").toUpperCase();
            String query2="Insert into "+TName2+" values(?)";
            String q2 ="create table "+TName2+" (ROOMID VARCHAR(100))";

            myCon=DriverManager.getConnection("jdbc:derby://localhost:1527/TTgen","rg","1234");            
            DatabaseMetaData dbm = myCon.getMetaData();
            ResultSet tables = dbm.getTables(null, null,TableName,null);
            ResultSet tables1 = dbm.getTables(null, null,TName2,null);

            String rname=RoomName.getText();
            String rid=RoomId.getText();
            
            if(!tables.next()){
            myStat=myCon.createStatement();
            myStat.executeUpdate(q1);    
            }
//            if(!tables1.next()){
//            myStat=myCon.createStatement();
//            myStat.executeUpdate(q2);    
//            }
            
            PreparedStatement insert=(PreparedStatement) myCon.prepareStatement(query);
            insert.setString(1,rname);
            insert.setString(2,rid);
            int row=insert.executeUpdate();
            /*
            PreparedStatement insert1=(PreparedStatement) myCon.prepareStatement(query2);
            insert1.setString(1,rid);
            int row1=insert1.executeUpdate();
            */
            
            
            RoomName.setText("");
            RoomId.setText("");
        }
        catch(SQLException e){
            e.printStackTrace();
        } 
        
        
        
    ViewData();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_AddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomsDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomsDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomsDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomsDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomsDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Delete;
    private javax.swing.JLabel Edit;
    private javax.swing.JTextField RoomId;
    private javax.swing.JTextField RoomName;
    public static javax.swing.JTable RoomsTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
