/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TTgen0;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;

/**
 *
 * @author ragha
 */
public class SignupPage extends javax.swing.JFrame {

    /**
     * Creates new form SignupPage
     */
    Connection myCon=null;
    Statement myStat=null;
    ResultSet myResult=null;
    
        
    public SignupPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cross = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        Show = new javax.swing.JLabel();
        Hide = new javax.swing.JLabel();
        Signup = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrossMouseClicked(evt);
            }
        });
        jPanel1.add(Cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 30, 30));

        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setBorder(null);
        Username.setCaretColor(new java.awt.Color(255, 255, 255));
        Username.setOpaque(false);
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 195, 220, 20));

        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setBorder(null);
        Email.setCaretColor(new java.awt.Color(255, 255, 255));
        Email.setOpaque(false);
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 266, 220, 20));

        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setBorder(null);
        Password.setCaretColor(new java.awt.Color(255, 255, 255));
        Password.setOpaque(false);
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 336, 200, 20));

        Show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowMouseClicked(evt);
            }
        });
        jPanel1.add(Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 332, 18, 18));

        Hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HideMouseClicked(evt);
            }
        });
        jPanel1.add(Hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 332, 18, 18));

        Signup.setContentAreaFilled(false);
        Signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Signup.setFocusable(false);
        Signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignupMouseClicked(evt);
            }
        });
        jPanel1.add(Signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 410, 110, 30));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/signup2.jpg"))); // NOI18N
        BG.setToolTipText("");
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowMouseClicked
    Hide.setVisible(true);
    Hide.setEnabled(true);
    Password.setEchoChar((char)0);
    ImageIcon A= new ImageIcon(getClass().getResource("/img/signup.jpg"));
    BG.setIcon(A);
    Show.setVisible(false);
    Show.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_ShowMouseClicked

    private void HideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HideMouseClicked
    Show.setVisible(true);
    Show.setEnabled(true);
    Password.setEchoChar((char)8226);
    ImageIcon A= new ImageIcon(getClass().getResource("/img/signup2.jpg"));
    BG.setIcon(A);
    Hide.setVisible(false);
    Hide.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_HideMouseClicked

    private void SignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignupMouseClicked
    if("".equals(Email.getText())||"".equals(Password.getText())||"".equals(Username.getText())){
                JOptionPane.showMessageDialog(this, "DATA IS NOT VALID","Error",JOptionPane.WARNING_MESSAGE);
            }
    else{
        String uname=Username.getText();
        String mail=Email.getText();
        String pass=Password.getText();
        String query = "INSERT INTO LogData values(?,?,?)";
                String q2 ="create table LogData (USERNAME VARCHAR(100),EMAIL VARCHAR(100),PASSWORD VARCHAR(100))";

        
        
        try{
            myCon=DriverManager.getConnection("jdbc:derby://localhost:1527/TTgen","rg","1234");
            myStat=myCon.createStatement();
            DatabaseMetaData dbm =myCon.getMetaData();
            ResultSet tables = dbm.getTables(null, null, "LogData", null);

            if(!tables.next()){
            myStat=myCon.createStatement();
            myStat.executeUpdate(q2);
            }
            
            PreparedStatement insert=(PreparedStatement) myCon.prepareStatement(query);
            insert.setString(1,uname);
            insert.setString(2,mail);
            insert.setString(3, pass);
            int row=insert.executeUpdate();
                  
            }
        catch(SQLException e){
            e.printStackTrace();
        }
        
    this.dispose();
    new LoginPage().setVisible(true);
    
    }
    
    }//GEN-LAST:event_SignupMouseClicked

    private void CrossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrossMouseClicked
    this.dispose();
    new LoginPage().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_CrossMouseClicked

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
    Password.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFocusGained

    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost
    if(Password.getText().isEmpty()){
            Password.setText("password");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Cross;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel Hide;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Show;
    private javax.swing.JButton Signup;
    private javax.swing.JTextField Username;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
