/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TTgen0;

import static TTgen0.Other.Days;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import static TTgen0.ClassesDatabase.ClassIds;

/**
 *
 * @author 91870
 */
public class TeachersDatabase extends javax.swing.JFrame {

    /**
     * Creates new form TeachersDatabase
     */
    Connection myCon=null;
    Statement myStat=null;
    ResultSet myResult=null;
    String TableName,TableName1;
    
    
    public TeachersDatabase() {
        initComponents();
        try{
        TableName=(Other.CourseName.getText()+"_"+Other.Branch.getText()+"_"+Other.Year.getText()+"_teachers").toUpperCase();}
        catch(NullPointerException e){
        TableName="btech_cse_1_teachers".toUpperCase();
        }
        
        try{
        TableName1=(Other.CourseName.getText()+"_"+Other.Branch.getText()+"_"+Other.Year.getText()+"_subjects").toUpperCase();}
        catch(NullPointerException e){
        TableName="btech_cse_1_subjects".toUpperCase();
        }
        addSubId();
        ViewData();
    }
    

    
    public void addSubId(){
        try{
        myCon=DriverManager.getConnection("jdbc:derby://localhost:1527/TTgen","rg","1234");
        myStat=myCon.createStatement();   
        myResult=myStat.executeQuery("Select SUBJECTID from "+TableName1);
        SubjectId.setModel(new DefaultComboBoxModel<>(new String[] {"Select"}));
        while(myResult.next())
        {
        SubjectId.addItem(myResult.getString("SUBJECTID"));
        }
        
        
       
        
    }
        catch(SQLException e){
            System.out.println("Table "+TableName1+" dows not exist");
                }
    
    }
    public void ViewData()
    {
        try{
        myCon=DriverManager.getConnection("jdbc:derby://localhost:1527/TTgen","rg","1234");
        myStat=myCon.createStatement();
        DatabaseMetaData dbm =myCon.getMetaData();
        ResultSet tables = dbm.getTables(null, null, TableName, null);
        
        if(tables.next()){
        myResult=myStat.executeQuery("Select * from "+TableName);
        TeachersTable.setModel(DbUtils.resultSetToTableModel(myResult));
        }
        else{
            DefaultTableModel dm = (DefaultTableModel) TeachersTable.getModel();
            dm.setRowCount(0);
        }
    }
        catch(SQLException e){
            e.printStackTrace();
                }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        StaffName = new javax.swing.JTextField();
        StaffCode = new javax.swing.JTextField();
        StaffId = new javax.swing.JTextField();
        Load = new javax.swing.JTextField();
        SubjectId = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TeachersTable = new javax.swing.JTable();
        Delete = new javax.swing.JLabel();
        Edit = new javax.swing.JLabel();
        Add = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StaffName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StaffName.setForeground(new java.awt.Color(255, 255, 255));
        StaffName.setBorder(null);
        StaffName.setOpaque(false);
        jPanel1.add(StaffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 220, 30));
        StaffName.getAccessibleContext().setAccessibleName("TextName");

        StaffCode.setEditable(false);
        StaffCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StaffCode.setForeground(new java.awt.Color(255, 255, 255));
        StaffCode.setBorder(null);
        jPanel1.add(StaffCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 90, 30));

        StaffId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StaffId.setForeground(new java.awt.Color(255, 255, 255));
        StaffId.setBorder(null);
        StaffId.setOpaque(false);
        jPanel1.add(StaffId, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 90, 30));

        Load.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Load.setForeground(new java.awt.Color(255, 255, 255));
        Load.setBorder(null);
        Load.setOpaque(false);
        jPanel1.add(Load, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 40, 30));

        jPanel1.add(SubjectId, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 389, 90, 30));

        TeachersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Staff Name", "Staff Id", "Subject Id", "Net Load", "Available Load"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TeachersTable);
        if (TeachersTable.getColumnModel().getColumnCount() > 0) {
            TeachersTable.getColumnModel().getColumn(0).setResizable(false);
            TeachersTable.getColumnModel().getColumn(0).setPreferredWidth(390);
            TeachersTable.getColumnModel().getColumn(1).setPreferredWidth(70);
            TeachersTable.getColumnModel().getColumn(2).setResizable(false);
            TeachersTable.getColumnModel().getColumn(2).setPreferredWidth(70);
            TeachersTable.getColumnModel().getColumn(3).setPreferredWidth(70);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 760, 320));

        Delete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Delete.setText("Delete");
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 478, 129, 30));

        Edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditMouseClicked(evt);
            }
        });
        jPanel1.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 478, 126, 32));

        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 478, 127, 30));

        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 478, 126, 30));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TeachersDatabase.jpg"))); // NOI18N
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("StaffDatabaseFrame");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        this.dispose();
        new Dashboard().setVisible(true);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_BackMouseClicked

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
    if("".equals(StaffId.getText()))
    {
    JOptionPane.showMessageDialog(this, "ENTER STAFF ID","Error",JOptionPane.WARNING_MESSAGE);}
    else{   
        try{
        String query="DELETE from "+TableName+" where staffid ='"+StaffId.getText()+"'";
        if(!SubjectId.getSelectedItem().toString().equals("Select")){query+=" and subjectid ='"+SubjectId.getSelectedItem().toString()+"'";}
        Statement add=myCon.createStatement();
        add.executeUpdate(query);
        StaffId.setText("");
    }                                   
   catch(SQLException e)
        {
            e.printStackTrace();
        }
    ViewData();
    }    // TODO add your handling code here:
    }//GEN-LAST:event_DeleteMouseClicked

    private void EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseClicked
    if("".equals(StaffId.getText())||SubjectId.getSelectedItem().toString().equals("Select"))
    {
    JOptionPane.showMessageDialog(this, "ENTER STAFF ID","Error",JOptionPane.WARNING_MESSAGE);}
    else{   
    
        try{
        String query="update "+TableName+" set net_load="+Integer.parseInt(Load.getText())+",avail_load="+Integer.parseInt(Load.getText())+" where staffid ='"+StaffId.getText()+"'";
        if(!SubjectId.getSelectedItem().toString().equals("Select")){query+=" and subjectid ='"+SubjectId.getSelectedItem().toString()+"'";}
        Statement update=myCon.createStatement();
        update.executeUpdate(query);
        StaffId.setText("");
        StaffName.setText("");
        Load.setText("");
        
       
    }                                   
   catch(SQLException e)
        {
            e.printStackTrace();
        }
    ViewData();
    }    // TODO add your handling code here:
    }//GEN-LAST:event_EditMouseClicked

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
    if("".equals(StaffName.getText())||"".equals(StaffId.getText())||"".equals(Load.getText())||SubjectId.getSelectedItem().toString().equals("Select"))
    {JOptionPane.showMessageDialog(this, "ENTER COPLETE DATA","Error",JOptionPane.WARNING_MESSAGE);
    }
    else{
        try{
            String query="Insert into "+TableName+" values(?,?,?,?,?)";
            String q1="create table "+TableName+" (STAFFNAME VARCHAR(100) ,STAFFID VARCHAR(100), SUBJECTID VARCHAR(100) ,NET_LOAD INTEGER , AVAIL_LOAD INTEGER)";
            String sname=StaffName.getText();
            String sid=StaffId.getText();
            int load=Integer.parseInt(Load.getText());
            
            String subid=SubjectId.getSelectedItem().toString();
            
            DatabaseMetaData dbm = myCon.getMetaData();
            ResultSet tables = dbm.getTables(null, null, TableName,null);
            
            if(!tables.next()){
            myStat=myCon.createStatement();
            myStat.executeUpdate(q1);    
            }
            
            PreparedStatement insert=(PreparedStatement) myCon.prepareStatement(query);
            insert.setString(1,sname);            
            insert.setString(2, sid);
            insert.setInt(4, load);
            insert.setString(3, subid);
            insert.setInt(5, load);
            int row=insert.executeUpdate();
            StaffId.setText("");
            StaffName.setText("");
            StaffCode.setText("");
            Load.setText("");  
            

            }
        catch(org.apache.derby.shared.common.error.DerbySQLIntegrityConstraintViolationException e){
            e.printStackTrace();
        }
        catch(SQLException e){
            e.printStackTrace();
        } 
        
    ViewData();
            }    // TODO add your handling code here:
    }//GEN-LAST:event_AddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeachersDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeachersDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeachersDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeachersDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeachersDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Delete;
    private javax.swing.JLabel Edit;
    private javax.swing.JTextField Load;
    private javax.swing.JTextField StaffCode;
    private javax.swing.JTextField StaffId;
    private javax.swing.JTextField StaffName;
    private javax.swing.JComboBox<String> SubjectId;
    private javax.swing.JTable TeachersTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
